// Code generated by go-swagger; DO NOT EDIT.

package directions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDirectionsForDirectionParams creates a new DirectionsForDirectionParams object
// with the default values initialized.
func NewDirectionsForDirectionParams() *DirectionsForDirectionParams {
	var ()
	return &DirectionsForDirectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDirectionsForDirectionParamsWithTimeout creates a new DirectionsForDirectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDirectionsForDirectionParamsWithTimeout(timeout time.Duration) *DirectionsForDirectionParams {
	var ()
	return &DirectionsForDirectionParams{

		timeout: timeout,
	}
}

// NewDirectionsForDirectionParamsWithContext creates a new DirectionsForDirectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDirectionsForDirectionParamsWithContext(ctx context.Context) *DirectionsForDirectionParams {
	var ()
	return &DirectionsForDirectionParams{

		Context: ctx,
	}
}

// NewDirectionsForDirectionParamsWithHTTPClient creates a new DirectionsForDirectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDirectionsForDirectionParamsWithHTTPClient(client *http.Client) *DirectionsForDirectionParams {
	var ()
	return &DirectionsForDirectionParams{
		HTTPClient: client,
	}
}

/*DirectionsForDirectionParams contains all the parameters to send to the API endpoint
for the directions for direction operation typically these are written to a http.Request
*/
type DirectionsForDirectionParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*DirectionID
	  Identifier of direction of travel; values returned by Directions API - /v3/directions/route/{route_id}

	*/
	DirectionID int32
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the directions for direction params
func (o *DirectionsForDirectionParams) WithTimeout(timeout time.Duration) *DirectionsForDirectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the directions for direction params
func (o *DirectionsForDirectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the directions for direction params
func (o *DirectionsForDirectionParams) WithContext(ctx context.Context) *DirectionsForDirectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the directions for direction params
func (o *DirectionsForDirectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the directions for direction params
func (o *DirectionsForDirectionParams) WithHTTPClient(client *http.Client) *DirectionsForDirectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the directions for direction params
func (o *DirectionsForDirectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the directions for direction params
func (o *DirectionsForDirectionParams) WithDevid(devid *string) *DirectionsForDirectionParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the directions for direction params
func (o *DirectionsForDirectionParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithDirectionID adds the directionID to the directions for direction params
func (o *DirectionsForDirectionParams) WithDirectionID(directionID int32) *DirectionsForDirectionParams {
	o.SetDirectionID(directionID)
	return o
}

// SetDirectionID adds the directionId to the directions for direction params
func (o *DirectionsForDirectionParams) SetDirectionID(directionID int32) {
	o.DirectionID = directionID
}

// WithSignature adds the signature to the directions for direction params
func (o *DirectionsForDirectionParams) WithSignature(signature *string) *DirectionsForDirectionParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the directions for direction params
func (o *DirectionsForDirectionParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the directions for direction params
func (o *DirectionsForDirectionParams) WithToken(token *string) *DirectionsForDirectionParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the directions for direction params
func (o *DirectionsForDirectionParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *DirectionsForDirectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	// path param direction_id
	if err := r.SetPathParam("direction_id", swag.FormatInt32(o.DirectionID)); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
