// Code generated by go-swagger; DO NOT EDIT.

package directions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDirectionsForRouteParams creates a new DirectionsForRouteParams object
// with the default values initialized.
func NewDirectionsForRouteParams() *DirectionsForRouteParams {
	var ()
	return &DirectionsForRouteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDirectionsForRouteParamsWithTimeout creates a new DirectionsForRouteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDirectionsForRouteParamsWithTimeout(timeout time.Duration) *DirectionsForRouteParams {
	var ()
	return &DirectionsForRouteParams{

		timeout: timeout,
	}
}

// NewDirectionsForRouteParamsWithContext creates a new DirectionsForRouteParams object
// with the default values initialized, and the ability to set a context for a request
func NewDirectionsForRouteParamsWithContext(ctx context.Context) *DirectionsForRouteParams {
	var ()
	return &DirectionsForRouteParams{

		Context: ctx,
	}
}

// NewDirectionsForRouteParamsWithHTTPClient creates a new DirectionsForRouteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDirectionsForRouteParamsWithHTTPClient(client *http.Client) *DirectionsForRouteParams {
	var ()
	return &DirectionsForRouteParams{
		HTTPClient: client,
	}
}

/*DirectionsForRouteParams contains all the parameters to send to the API endpoint
for the directions for route operation typically these are written to a http.Request
*/
type DirectionsForRouteParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*RouteID
	  Identifier of route; values returned by Routes API - v3/routes

	*/
	RouteID int32
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the directions for route params
func (o *DirectionsForRouteParams) WithTimeout(timeout time.Duration) *DirectionsForRouteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the directions for route params
func (o *DirectionsForRouteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the directions for route params
func (o *DirectionsForRouteParams) WithContext(ctx context.Context) *DirectionsForRouteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the directions for route params
func (o *DirectionsForRouteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the directions for route params
func (o *DirectionsForRouteParams) WithHTTPClient(client *http.Client) *DirectionsForRouteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the directions for route params
func (o *DirectionsForRouteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the directions for route params
func (o *DirectionsForRouteParams) WithDevid(devid *string) *DirectionsForRouteParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the directions for route params
func (o *DirectionsForRouteParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithRouteID adds the routeID to the directions for route params
func (o *DirectionsForRouteParams) WithRouteID(routeID int32) *DirectionsForRouteParams {
	o.SetRouteID(routeID)
	return o
}

// SetRouteID adds the routeId to the directions for route params
func (o *DirectionsForRouteParams) SetRouteID(routeID int32) {
	o.RouteID = routeID
}

// WithSignature adds the signature to the directions for route params
func (o *DirectionsForRouteParams) WithSignature(signature *string) *DirectionsForRouteParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the directions for route params
func (o *DirectionsForRouteParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the directions for route params
func (o *DirectionsForRouteParams) WithToken(token *string) *DirectionsForRouteParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the directions for route params
func (o *DirectionsForRouteParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *DirectionsForRouteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	// path param route_id
	if err := r.SetPathParam("route_id", swag.FormatInt32(o.RouteID)); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
