// Code generated by go-swagger; DO NOT EDIT.

package directions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new directions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for directions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DirectionsForDirection views all routes for a direction of travel
*/
func (a *Client) DirectionsForDirection(params *DirectionsForDirectionParams) (*DirectionsForDirectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDirectionsForDirectionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Directions_ForDirection",
		Method:             "GET",
		PathPattern:        "/v3/directions/{direction_id}",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DirectionsForDirectionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DirectionsForDirectionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Directions_ForDirection: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DirectionsForDirectionAndType views all routes of a particular type for a direction of travel
*/
func (a *Client) DirectionsForDirectionAndType(params *DirectionsForDirectionAndTypeParams) (*DirectionsForDirectionAndTypeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDirectionsForDirectionAndTypeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Directions_ForDirectionAndType",
		Method:             "GET",
		PathPattern:        "/v3/directions/{direction_id}/route_type/{route_type}",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DirectionsForDirectionAndTypeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DirectionsForDirectionAndTypeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Directions_ForDirectionAndType: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DirectionsForRoute views directions that a route travels in
*/
func (a *Client) DirectionsForRoute(params *DirectionsForRouteParams) (*DirectionsForRouteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDirectionsForRouteParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Directions_ForRoute",
		Method:             "GET",
		PathPattern:        "/v3/directions/route/{route_id}",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DirectionsForRouteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DirectionsForRouteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Directions_ForRoute: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
