// Code generated by go-swagger; DO NOT EDIT.

package departures

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new departures API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for departures API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
DeparturesGetForStop views departures for all routes from a stop
*/
func (a *Client) DeparturesGetForStop(params *DeparturesGetForStopParams) (*DeparturesGetForStopOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeparturesGetForStopParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Departures_GetForStop",
		Method:             "GET",
		PathPattern:        "/v3/departures/route_type/{route_type}/stop/{stop_id}",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeparturesGetForStopReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeparturesGetForStopOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Departures_GetForStop: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeparturesGetForStopAndRoute views departures for a specific route from a stop
*/
func (a *Client) DeparturesGetForStopAndRoute(params *DeparturesGetForStopAndRouteParams) (*DeparturesGetForStopAndRouteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeparturesGetForStopAndRouteParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Departures_GetForStopAndRoute",
		Method:             "GET",
		PathPattern:        "/v3/departures/route_type/{route_type}/stop/{stop_id}/route/{route_id}",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeparturesGetForStopAndRouteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeparturesGetForStopAndRouteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Departures_GetForStopAndRoute: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
