// Code generated by go-swagger; DO NOT EDIT.

package stops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ronny/ptvapi/models"
)

// StopsStopDetailsReader is a Reader for the StopsStopDetails structure.
type StopsStopDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopsStopDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStopsStopDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStopsStopDetailsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewStopsStopDetailsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopsStopDetailsOK creates a StopsStopDetailsOK with default headers values
func NewStopsStopDetailsOK() *StopsStopDetailsOK {
	return &StopsStopDetailsOK{}
}

/*StopsStopDetailsOK handles this case with default header values.

Stop location, amenity and accessibility facility information for the specified stop (metropolitan and V/Line stations only).
*/
type StopsStopDetailsOK struct {
	Payload *models.V3StopResponse
}

func (o *StopsStopDetailsOK) Error() string {
	return fmt.Sprintf("[GET /v3/stops/{stop_id}/route_type/{route_type}][%d] stopsStopDetailsOK  %+v", 200, o.Payload)
}

func (o *StopsStopDetailsOK) GetPayload() *models.V3StopResponse {
	return o.Payload
}

func (o *StopsStopDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3StopResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopsStopDetailsBadRequest creates a StopsStopDetailsBadRequest with default headers values
func NewStopsStopDetailsBadRequest() *StopsStopDetailsBadRequest {
	return &StopsStopDetailsBadRequest{}
}

/*StopsStopDetailsBadRequest handles this case with default header values.

Invalid Request
*/
type StopsStopDetailsBadRequest struct {
	Payload *models.V3ErrorResponse
}

func (o *StopsStopDetailsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v3/stops/{stop_id}/route_type/{route_type}][%d] stopsStopDetailsBadRequest  %+v", 400, o.Payload)
}

func (o *StopsStopDetailsBadRequest) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *StopsStopDetailsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStopsStopDetailsForbidden creates a StopsStopDetailsForbidden with default headers values
func NewStopsStopDetailsForbidden() *StopsStopDetailsForbidden {
	return &StopsStopDetailsForbidden{}
}

/*StopsStopDetailsForbidden handles this case with default header values.

Access Denied
*/
type StopsStopDetailsForbidden struct {
	Payload *models.V3ErrorResponse
}

func (o *StopsStopDetailsForbidden) Error() string {
	return fmt.Sprintf("[GET /v3/stops/{stop_id}/route_type/{route_type}][%d] stopsStopDetailsForbidden  %+v", 403, o.Payload)
}

func (o *StopsStopDetailsForbidden) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *StopsStopDetailsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
