// Code generated by go-swagger; DO NOT EDIT.

package stops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStopsStopsByGeolocationParams creates a new StopsStopsByGeolocationParams object
// with the default values initialized.
func NewStopsStopsByGeolocationParams() *StopsStopsByGeolocationParams {
	var ()
	return &StopsStopsByGeolocationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStopsStopsByGeolocationParamsWithTimeout creates a new StopsStopsByGeolocationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStopsStopsByGeolocationParamsWithTimeout(timeout time.Duration) *StopsStopsByGeolocationParams {
	var ()
	return &StopsStopsByGeolocationParams{

		timeout: timeout,
	}
}

// NewStopsStopsByGeolocationParamsWithContext creates a new StopsStopsByGeolocationParams object
// with the default values initialized, and the ability to set a context for a request
func NewStopsStopsByGeolocationParamsWithContext(ctx context.Context) *StopsStopsByGeolocationParams {
	var ()
	return &StopsStopsByGeolocationParams{

		Context: ctx,
	}
}

// NewStopsStopsByGeolocationParamsWithHTTPClient creates a new StopsStopsByGeolocationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStopsStopsByGeolocationParamsWithHTTPClient(client *http.Client) *StopsStopsByGeolocationParams {
	var ()
	return &StopsStopsByGeolocationParams{
		HTTPClient: client,
	}
}

/*StopsStopsByGeolocationParams contains all the parameters to send to the API endpoint
for the stops stops by geolocation operation typically these are written to a http.Request
*/
type StopsStopsByGeolocationParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*Latitude
	  Geographic coordinate of latitude

	*/
	Latitude float32
	/*Longitude
	  Geographic coordinate of longitude

	*/
	Longitude float32
	/*MaxDistance
	  Filter by maximum distance (in metres) from location specified via latitude and longitude parameters (default = 300)

	*/
	MaxDistance *float64
	/*MaxResults
	  Maximum number of results returned (default = 30)

	*/
	MaxResults *int32
	/*RouteTypes
	  Filter by route_type; values returned via RouteTypes API

	*/
	RouteTypes []int32
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*StopDisruptions
	  Indicates if stop disruption information will be returned (default = false)

	*/
	StopDisruptions *bool
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithTimeout(timeout time.Duration) *StopsStopsByGeolocationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithContext(ctx context.Context) *StopsStopsByGeolocationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithHTTPClient(client *http.Client) *StopsStopsByGeolocationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithDevid(devid *string) *StopsStopsByGeolocationParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithLatitude adds the latitude to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithLatitude(latitude float32) *StopsStopsByGeolocationParams {
	o.SetLatitude(latitude)
	return o
}

// SetLatitude adds the latitude to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetLatitude(latitude float32) {
	o.Latitude = latitude
}

// WithLongitude adds the longitude to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithLongitude(longitude float32) *StopsStopsByGeolocationParams {
	o.SetLongitude(longitude)
	return o
}

// SetLongitude adds the longitude to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetLongitude(longitude float32) {
	o.Longitude = longitude
}

// WithMaxDistance adds the maxDistance to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithMaxDistance(maxDistance *float64) *StopsStopsByGeolocationParams {
	o.SetMaxDistance(maxDistance)
	return o
}

// SetMaxDistance adds the maxDistance to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetMaxDistance(maxDistance *float64) {
	o.MaxDistance = maxDistance
}

// WithMaxResults adds the maxResults to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithMaxResults(maxResults *int32) *StopsStopsByGeolocationParams {
	o.SetMaxResults(maxResults)
	return o
}

// SetMaxResults adds the maxResults to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetMaxResults(maxResults *int32) {
	o.MaxResults = maxResults
}

// WithRouteTypes adds the routeTypes to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithRouteTypes(routeTypes []int32) *StopsStopsByGeolocationParams {
	o.SetRouteTypes(routeTypes)
	return o
}

// SetRouteTypes adds the routeTypes to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetRouteTypes(routeTypes []int32) {
	o.RouteTypes = routeTypes
}

// WithSignature adds the signature to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithSignature(signature *string) *StopsStopsByGeolocationParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithStopDisruptions adds the stopDisruptions to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithStopDisruptions(stopDisruptions *bool) *StopsStopsByGeolocationParams {
	o.SetStopDisruptions(stopDisruptions)
	return o
}

// SetStopDisruptions adds the stopDisruptions to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetStopDisruptions(stopDisruptions *bool) {
	o.StopDisruptions = stopDisruptions
}

// WithToken adds the token to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) WithToken(token *string) *StopsStopsByGeolocationParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the stops stops by geolocation params
func (o *StopsStopsByGeolocationParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *StopsStopsByGeolocationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	// path param latitude
	if err := r.SetPathParam("latitude", swag.FormatFloat32(o.Latitude)); err != nil {
		return err
	}

	// path param longitude
	if err := r.SetPathParam("longitude", swag.FormatFloat32(o.Longitude)); err != nil {
		return err
	}

	if o.MaxDistance != nil {

		// query param max_distance
		var qrMaxDistance float64
		if o.MaxDistance != nil {
			qrMaxDistance = *o.MaxDistance
		}
		qMaxDistance := swag.FormatFloat64(qrMaxDistance)
		if qMaxDistance != "" {
			if err := r.SetQueryParam("max_distance", qMaxDistance); err != nil {
				return err
			}
		}

	}

	if o.MaxResults != nil {

		// query param max_results
		var qrMaxResults int32
		if o.MaxResults != nil {
			qrMaxResults = *o.MaxResults
		}
		qMaxResults := swag.FormatInt32(qrMaxResults)
		if qMaxResults != "" {
			if err := r.SetQueryParam("max_results", qMaxResults); err != nil {
				return err
			}
		}

	}

	var valuesRouteTypes []string
	for _, v := range o.RouteTypes {
		valuesRouteTypes = append(valuesRouteTypes, swag.FormatInt32(v))
	}

	joinedRouteTypes := swag.JoinByFormat(valuesRouteTypes, "multi")
	// query array param route_types
	if err := r.SetQueryParam("route_types", joinedRouteTypes...); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.StopDisruptions != nil {

		// query param stop_disruptions
		var qrStopDisruptions bool
		if o.StopDisruptions != nil {
			qrStopDisruptions = *o.StopDisruptions
		}
		qStopDisruptions := swag.FormatBool(qrStopDisruptions)
		if qStopDisruptions != "" {
			if err := r.SetQueryParam("stop_disruptions", qStopDisruptions); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
