// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRoutesOneOrMoreRoutesParams creates a new RoutesOneOrMoreRoutesParams object
// with the default values initialized.
func NewRoutesOneOrMoreRoutesParams() *RoutesOneOrMoreRoutesParams {
	var ()
	return &RoutesOneOrMoreRoutesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRoutesOneOrMoreRoutesParamsWithTimeout creates a new RoutesOneOrMoreRoutesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRoutesOneOrMoreRoutesParamsWithTimeout(timeout time.Duration) *RoutesOneOrMoreRoutesParams {
	var ()
	return &RoutesOneOrMoreRoutesParams{

		timeout: timeout,
	}
}

// NewRoutesOneOrMoreRoutesParamsWithContext creates a new RoutesOneOrMoreRoutesParams object
// with the default values initialized, and the ability to set a context for a request
func NewRoutesOneOrMoreRoutesParamsWithContext(ctx context.Context) *RoutesOneOrMoreRoutesParams {
	var ()
	return &RoutesOneOrMoreRoutesParams{

		Context: ctx,
	}
}

// NewRoutesOneOrMoreRoutesParamsWithHTTPClient creates a new RoutesOneOrMoreRoutesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRoutesOneOrMoreRoutesParamsWithHTTPClient(client *http.Client) *RoutesOneOrMoreRoutesParams {
	var ()
	return &RoutesOneOrMoreRoutesParams{
		HTTPClient: client,
	}
}

/*RoutesOneOrMoreRoutesParams contains all the parameters to send to the API endpoint
for the routes one or more routes operation typically these are written to a http.Request
*/
type RoutesOneOrMoreRoutesParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*RouteName
	  Filter by name  of route (accepts partial route name matches)

	*/
	RouteName *string
	/*RouteTypes
	  Filter by route_type; values returned via RouteTypes API

	*/
	RouteTypes []int32
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) WithTimeout(timeout time.Duration) *RoutesOneOrMoreRoutesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) WithContext(ctx context.Context) *RoutesOneOrMoreRoutesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) WithHTTPClient(client *http.Client) *RoutesOneOrMoreRoutesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) WithDevid(devid *string) *RoutesOneOrMoreRoutesParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithRouteName adds the routeName to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) WithRouteName(routeName *string) *RoutesOneOrMoreRoutesParams {
	o.SetRouteName(routeName)
	return o
}

// SetRouteName adds the routeName to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) SetRouteName(routeName *string) {
	o.RouteName = routeName
}

// WithRouteTypes adds the routeTypes to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) WithRouteTypes(routeTypes []int32) *RoutesOneOrMoreRoutesParams {
	o.SetRouteTypes(routeTypes)
	return o
}

// SetRouteTypes adds the routeTypes to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) SetRouteTypes(routeTypes []int32) {
	o.RouteTypes = routeTypes
}

// WithSignature adds the signature to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) WithSignature(signature *string) *RoutesOneOrMoreRoutesParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) WithToken(token *string) *RoutesOneOrMoreRoutesParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the routes one or more routes params
func (o *RoutesOneOrMoreRoutesParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *RoutesOneOrMoreRoutesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	if o.RouteName != nil {

		// query param route_name
		var qrRouteName string
		if o.RouteName != nil {
			qrRouteName = *o.RouteName
		}
		qRouteName := qrRouteName
		if qRouteName != "" {
			if err := r.SetQueryParam("route_name", qRouteName); err != nil {
				return err
			}
		}

	}

	var valuesRouteTypes []string
	for _, v := range o.RouteTypes {
		valuesRouteTypes = append(valuesRouteTypes, swag.FormatInt32(v))
	}

	joinedRouteTypes := swag.JoinByFormat(valuesRouteTypes, "multi")
	// query array param route_types
	if err := r.SetQueryParam("route_types", joinedRouteTypes...); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
