// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new routes API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for routes API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
RoutesOneOrMoreRoutes views route names and numbers for all routes
*/
func (a *Client) RoutesOneOrMoreRoutes(params *RoutesOneOrMoreRoutesParams) (*RoutesOneOrMoreRoutesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRoutesOneOrMoreRoutesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Routes_OneOrMoreRoutes",
		Method:             "GET",
		PathPattern:        "/v3/routes",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RoutesOneOrMoreRoutesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RoutesOneOrMoreRoutesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Routes_OneOrMoreRoutes: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RoutesRouteFromID views route name and number for specific route ID
*/
func (a *Client) RoutesRouteFromID(params *RoutesRouteFromIDParams) (*RoutesRouteFromIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRoutesRouteFromIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Routes_RouteFromId",
		Method:             "GET",
		PathPattern:        "/v3/routes/{route_id}",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &RoutesRouteFromIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RoutesRouteFromIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Routes_RouteFromId: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
