// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ronny/ptvapi/v3/models"
)

// RoutesRouteFromIDReader is a Reader for the RoutesRouteFromID structure.
type RoutesRouteFromIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoutesRouteFromIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRoutesRouteFromIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRoutesRouteFromIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRoutesRouteFromIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRoutesRouteFromIDOK creates a RoutesRouteFromIDOK with default headers values
func NewRoutesRouteFromIDOK() *RoutesRouteFromIDOK {
	return &RoutesRouteFromIDOK{}
}

/*RoutesRouteFromIDOK handles this case with default header values.

The route name and number for the specified route ID.
*/
type RoutesRouteFromIDOK struct {
	Payload *models.V3RouteResponse
}

func (o *RoutesRouteFromIDOK) Error() string {
	return fmt.Sprintf("[GET /v3/routes/{route_id}][%d] routesRouteFromIdOK  %+v", 200, o.Payload)
}

func (o *RoutesRouteFromIDOK) GetPayload() *models.V3RouteResponse {
	return o.Payload
}

func (o *RoutesRouteFromIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3RouteResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRoutesRouteFromIDBadRequest creates a RoutesRouteFromIDBadRequest with default headers values
func NewRoutesRouteFromIDBadRequest() *RoutesRouteFromIDBadRequest {
	return &RoutesRouteFromIDBadRequest{}
}

/*RoutesRouteFromIDBadRequest handles this case with default header values.

Invalid Request
*/
type RoutesRouteFromIDBadRequest struct {
	Payload *models.V3ErrorResponse
}

func (o *RoutesRouteFromIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /v3/routes/{route_id}][%d] routesRouteFromIdBadRequest  %+v", 400, o.Payload)
}

func (o *RoutesRouteFromIDBadRequest) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *RoutesRouteFromIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRoutesRouteFromIDForbidden creates a RoutesRouteFromIDForbidden with default headers values
func NewRoutesRouteFromIDForbidden() *RoutesRouteFromIDForbidden {
	return &RoutesRouteFromIDForbidden{}
}

/*RoutesRouteFromIDForbidden handles this case with default header values.

Access Denied
*/
type RoutesRouteFromIDForbidden struct {
	Payload *models.V3ErrorResponse
}

func (o *RoutesRouteFromIDForbidden) Error() string {
	return fmt.Sprintf("[GET /v3/routes/{route_id}][%d] routesRouteFromIdForbidden  %+v", 403, o.Payload)
}

func (o *RoutesRouteFromIDForbidden) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *RoutesRouteFromIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
