// Code generated by go-swagger; DO NOT EDIT.

package outlets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new outlets API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for outlets API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
OutletsGetAllOutlets lists all ticket outlets
*/
func (a *Client) OutletsGetAllOutlets(params *OutletsGetAllOutletsParams) (*OutletsGetAllOutletsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOutletsGetAllOutletsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Outlets_GetAllOutlets",
		Method:             "GET",
		PathPattern:        "/v3/outlets",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &OutletsGetAllOutletsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OutletsGetAllOutletsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Outlets_GetAllOutlets: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
OutletsGetOutletsByGeolocation lists ticket outlets near a specific location
*/
func (a *Client) OutletsGetOutletsByGeolocation(params *OutletsGetOutletsByGeolocationParams) (*OutletsGetOutletsByGeolocationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewOutletsGetOutletsByGeolocationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Outlets_GetOutletsByGeolocation",
		Method:             "GET",
		PathPattern:        "/v3/outlets/location/{latitude},{longitude}",
		ProducesMediaTypes: []string{"application/json", "text/html", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &OutletsGetOutletsByGeolocationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*OutletsGetOutletsByGeolocationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for Outlets_GetOutletsByGeolocation: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
