// Code generated by go-swagger; DO NOT EDIT.

package disruptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDisruptionsGetDisruptionsByRouteAndStopParams creates a new DisruptionsGetDisruptionsByRouteAndStopParams object
// with the default values initialized.
func NewDisruptionsGetDisruptionsByRouteAndStopParams() *DisruptionsGetDisruptionsByRouteAndStopParams {
	var ()
	return &DisruptionsGetDisruptionsByRouteAndStopParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDisruptionsGetDisruptionsByRouteAndStopParamsWithTimeout creates a new DisruptionsGetDisruptionsByRouteAndStopParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDisruptionsGetDisruptionsByRouteAndStopParamsWithTimeout(timeout time.Duration) *DisruptionsGetDisruptionsByRouteAndStopParams {
	var ()
	return &DisruptionsGetDisruptionsByRouteAndStopParams{

		timeout: timeout,
	}
}

// NewDisruptionsGetDisruptionsByRouteAndStopParamsWithContext creates a new DisruptionsGetDisruptionsByRouteAndStopParams object
// with the default values initialized, and the ability to set a context for a request
func NewDisruptionsGetDisruptionsByRouteAndStopParamsWithContext(ctx context.Context) *DisruptionsGetDisruptionsByRouteAndStopParams {
	var ()
	return &DisruptionsGetDisruptionsByRouteAndStopParams{

		Context: ctx,
	}
}

// NewDisruptionsGetDisruptionsByRouteAndStopParamsWithHTTPClient creates a new DisruptionsGetDisruptionsByRouteAndStopParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDisruptionsGetDisruptionsByRouteAndStopParamsWithHTTPClient(client *http.Client) *DisruptionsGetDisruptionsByRouteAndStopParams {
	var ()
	return &DisruptionsGetDisruptionsByRouteAndStopParams{
		HTTPClient: client,
	}
}

/*DisruptionsGetDisruptionsByRouteAndStopParams contains all the parameters to send to the API endpoint
for the disruptions get disruptions by route and stop operation typically these are written to a http.Request
*/
type DisruptionsGetDisruptionsByRouteAndStopParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*DisruptionStatus
	  Filter by status of disruption

	*/
	DisruptionStatus *string
	/*RouteID
	  Identifier of route; values returned by Routes API - v3/routes

	*/
	RouteID int32
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*StopID
	  Identifier of stop; values returned by Stops API - v3/stops

	*/
	StopID int32
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithTimeout(timeout time.Duration) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithContext(ctx context.Context) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithHTTPClient(client *http.Client) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithDevid(devid *string) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithDisruptionStatus adds the disruptionStatus to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithDisruptionStatus(disruptionStatus *string) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetDisruptionStatus(disruptionStatus)
	return o
}

// SetDisruptionStatus adds the disruptionStatus to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetDisruptionStatus(disruptionStatus *string) {
	o.DisruptionStatus = disruptionStatus
}

// WithRouteID adds the routeID to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithRouteID(routeID int32) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetRouteID(routeID)
	return o
}

// SetRouteID adds the routeId to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetRouteID(routeID int32) {
	o.RouteID = routeID
}

// WithSignature adds the signature to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithSignature(signature *string) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithStopID adds the stopID to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithStopID(stopID int32) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetStopID(stopID)
	return o
}

// SetStopID adds the stopId to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetStopID(stopID int32) {
	o.StopID = stopID
}

// WithToken adds the token to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WithToken(token *string) *DisruptionsGetDisruptionsByRouteAndStopParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the disruptions get disruptions by route and stop params
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *DisruptionsGetDisruptionsByRouteAndStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	if o.DisruptionStatus != nil {

		// query param disruption_status
		var qrDisruptionStatus string
		if o.DisruptionStatus != nil {
			qrDisruptionStatus = *o.DisruptionStatus
		}
		qDisruptionStatus := qrDisruptionStatus
		if qDisruptionStatus != "" {
			if err := r.SetQueryParam("disruption_status", qDisruptionStatus); err != nil {
				return err
			}
		}

	}

	// path param route_id
	if err := r.SetPathParam("route_id", swag.FormatInt32(o.RouteID)); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	// path param stop_id
	if err := r.SetPathParam("stop_id", swag.FormatInt32(o.StopID)); err != nil {
		return err
	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
