// Code generated by go-swagger; DO NOT EDIT.

package disruptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ronny/ptvapi/models"
)

// DisruptionsGetDisruptionsByStopReader is a Reader for the DisruptionsGetDisruptionsByStop structure.
type DisruptionsGetDisruptionsByStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisruptionsGetDisruptionsByStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDisruptionsGetDisruptionsByStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDisruptionsGetDisruptionsByStopBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDisruptionsGetDisruptionsByStopForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDisruptionsGetDisruptionsByStopOK creates a DisruptionsGetDisruptionsByStopOK with default headers values
func NewDisruptionsGetDisruptionsByStopOK() *DisruptionsGetDisruptionsByStopOK {
	return &DisruptionsGetDisruptionsByStopOK{}
}

/*DisruptionsGetDisruptionsByStopOK handles this case with default header values.

All disruption information (if any exists) for the specified stop.
*/
type DisruptionsGetDisruptionsByStopOK struct {
	Payload *models.V3DisruptionsResponse
}

func (o *DisruptionsGetDisruptionsByStopOK) Error() string {
	return fmt.Sprintf("[GET /v3/disruptions/stop/{stop_id}][%d] disruptionsGetDisruptionsByStopOK  %+v", 200, o.Payload)
}

func (o *DisruptionsGetDisruptionsByStopOK) GetPayload() *models.V3DisruptionsResponse {
	return o.Payload
}

func (o *DisruptionsGetDisruptionsByStopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3DisruptionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisruptionsGetDisruptionsByStopBadRequest creates a DisruptionsGetDisruptionsByStopBadRequest with default headers values
func NewDisruptionsGetDisruptionsByStopBadRequest() *DisruptionsGetDisruptionsByStopBadRequest {
	return &DisruptionsGetDisruptionsByStopBadRequest{}
}

/*DisruptionsGetDisruptionsByStopBadRequest handles this case with default header values.

Invalid Request
*/
type DisruptionsGetDisruptionsByStopBadRequest struct {
	Payload *models.V3ErrorResponse
}

func (o *DisruptionsGetDisruptionsByStopBadRequest) Error() string {
	return fmt.Sprintf("[GET /v3/disruptions/stop/{stop_id}][%d] disruptionsGetDisruptionsByStopBadRequest  %+v", 400, o.Payload)
}

func (o *DisruptionsGetDisruptionsByStopBadRequest) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *DisruptionsGetDisruptionsByStopBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisruptionsGetDisruptionsByStopForbidden creates a DisruptionsGetDisruptionsByStopForbidden with default headers values
func NewDisruptionsGetDisruptionsByStopForbidden() *DisruptionsGetDisruptionsByStopForbidden {
	return &DisruptionsGetDisruptionsByStopForbidden{}
}

/*DisruptionsGetDisruptionsByStopForbidden handles this case with default header values.

Access Denied
*/
type DisruptionsGetDisruptionsByStopForbidden struct {
	Payload *models.V3ErrorResponse
}

func (o *DisruptionsGetDisruptionsByStopForbidden) Error() string {
	return fmt.Sprintf("[GET /v3/disruptions/stop/{stop_id}][%d] disruptionsGetDisruptionsByStopForbidden  %+v", 403, o.Payload)
}

func (o *DisruptionsGetDisruptionsByStopForbidden) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *DisruptionsGetDisruptionsByStopForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
