// Code generated by go-swagger; DO NOT EDIT.

package disruptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ronny/ptvapi/v3/models"
)

// DisruptionsGetAllDisruptionsReader is a Reader for the DisruptionsGetAllDisruptions structure.
type DisruptionsGetAllDisruptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisruptionsGetAllDisruptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDisruptionsGetAllDisruptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDisruptionsGetAllDisruptionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDisruptionsGetAllDisruptionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDisruptionsGetAllDisruptionsOK creates a DisruptionsGetAllDisruptionsOK with default headers values
func NewDisruptionsGetAllDisruptionsOK() *DisruptionsGetAllDisruptionsOK {
	return &DisruptionsGetAllDisruptionsOK{}
}

/*DisruptionsGetAllDisruptionsOK handles this case with default header values.

All disruption information for all route types.
*/
type DisruptionsGetAllDisruptionsOK struct {
	Payload *models.V3DisruptionsResponse
}

func (o *DisruptionsGetAllDisruptionsOK) Error() string {
	return fmt.Sprintf("[GET /v3/disruptions][%d] disruptionsGetAllDisruptionsOK  %+v", 200, o.Payload)
}

func (o *DisruptionsGetAllDisruptionsOK) GetPayload() *models.V3DisruptionsResponse {
	return o.Payload
}

func (o *DisruptionsGetAllDisruptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3DisruptionsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisruptionsGetAllDisruptionsBadRequest creates a DisruptionsGetAllDisruptionsBadRequest with default headers values
func NewDisruptionsGetAllDisruptionsBadRequest() *DisruptionsGetAllDisruptionsBadRequest {
	return &DisruptionsGetAllDisruptionsBadRequest{}
}

/*DisruptionsGetAllDisruptionsBadRequest handles this case with default header values.

Invalid Request
*/
type DisruptionsGetAllDisruptionsBadRequest struct {
	Payload *models.V3ErrorResponse
}

func (o *DisruptionsGetAllDisruptionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v3/disruptions][%d] disruptionsGetAllDisruptionsBadRequest  %+v", 400, o.Payload)
}

func (o *DisruptionsGetAllDisruptionsBadRequest) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *DisruptionsGetAllDisruptionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisruptionsGetAllDisruptionsForbidden creates a DisruptionsGetAllDisruptionsForbidden with default headers values
func NewDisruptionsGetAllDisruptionsForbidden() *DisruptionsGetAllDisruptionsForbidden {
	return &DisruptionsGetAllDisruptionsForbidden{}
}

/*DisruptionsGetAllDisruptionsForbidden handles this case with default header values.

Access Denied
*/
type DisruptionsGetAllDisruptionsForbidden struct {
	Payload *models.V3ErrorResponse
}

func (o *DisruptionsGetAllDisruptionsForbidden) Error() string {
	return fmt.Sprintf("[GET /v3/disruptions][%d] disruptionsGetAllDisruptionsForbidden  %+v", 403, o.Payload)
}

func (o *DisruptionsGetAllDisruptionsForbidden) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *DisruptionsGetAllDisruptionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
