// Code generated by go-swagger; DO NOT EDIT.

package disruptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDisruptionsGetDisruptionByIDParams creates a new DisruptionsGetDisruptionByIDParams object
// with the default values initialized.
func NewDisruptionsGetDisruptionByIDParams() *DisruptionsGetDisruptionByIDParams {
	var ()
	return &DisruptionsGetDisruptionByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDisruptionsGetDisruptionByIDParamsWithTimeout creates a new DisruptionsGetDisruptionByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDisruptionsGetDisruptionByIDParamsWithTimeout(timeout time.Duration) *DisruptionsGetDisruptionByIDParams {
	var ()
	return &DisruptionsGetDisruptionByIDParams{

		timeout: timeout,
	}
}

// NewDisruptionsGetDisruptionByIDParamsWithContext creates a new DisruptionsGetDisruptionByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDisruptionsGetDisruptionByIDParamsWithContext(ctx context.Context) *DisruptionsGetDisruptionByIDParams {
	var ()
	return &DisruptionsGetDisruptionByIDParams{

		Context: ctx,
	}
}

// NewDisruptionsGetDisruptionByIDParamsWithHTTPClient creates a new DisruptionsGetDisruptionByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDisruptionsGetDisruptionByIDParamsWithHTTPClient(client *http.Client) *DisruptionsGetDisruptionByIDParams {
	var ()
	return &DisruptionsGetDisruptionByIDParams{
		HTTPClient: client,
	}
}

/*DisruptionsGetDisruptionByIDParams contains all the parameters to send to the API endpoint
for the disruptions get disruption by Id operation typically these are written to a http.Request
*/
type DisruptionsGetDisruptionByIDParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*DisruptionID
	  Identifier of disruption; values returned by Disruptions API - /v3/disruptions OR /v3/disruptions/route/{route_id}

	*/
	DisruptionID int64
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) WithTimeout(timeout time.Duration) *DisruptionsGetDisruptionByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) WithContext(ctx context.Context) *DisruptionsGetDisruptionByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) WithHTTPClient(client *http.Client) *DisruptionsGetDisruptionByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) WithDevid(devid *string) *DisruptionsGetDisruptionByIDParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithDisruptionID adds the disruptionID to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) WithDisruptionID(disruptionID int64) *DisruptionsGetDisruptionByIDParams {
	o.SetDisruptionID(disruptionID)
	return o
}

// SetDisruptionID adds the disruptionId to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) SetDisruptionID(disruptionID int64) {
	o.DisruptionID = disruptionID
}

// WithSignature adds the signature to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) WithSignature(signature *string) *DisruptionsGetDisruptionByIDParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) WithToken(token *string) *DisruptionsGetDisruptionByIDParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the disruptions get disruption by Id params
func (o *DisruptionsGetDisruptionByIDParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *DisruptionsGetDisruptionByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	// path param disruption_id
	if err := r.SetPathParam("disruption_id", swag.FormatInt64(o.DisruptionID)); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
