// Code generated by go-swagger; DO NOT EDIT.

package route_types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRouteTypesGetRouteTypesParams creates a new RouteTypesGetRouteTypesParams object
// with the default values initialized.
func NewRouteTypesGetRouteTypesParams() *RouteTypesGetRouteTypesParams {
	var ()
	return &RouteTypesGetRouteTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRouteTypesGetRouteTypesParamsWithTimeout creates a new RouteTypesGetRouteTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRouteTypesGetRouteTypesParamsWithTimeout(timeout time.Duration) *RouteTypesGetRouteTypesParams {
	var ()
	return &RouteTypesGetRouteTypesParams{

		timeout: timeout,
	}
}

// NewRouteTypesGetRouteTypesParamsWithContext creates a new RouteTypesGetRouteTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewRouteTypesGetRouteTypesParamsWithContext(ctx context.Context) *RouteTypesGetRouteTypesParams {
	var ()
	return &RouteTypesGetRouteTypesParams{

		Context: ctx,
	}
}

// NewRouteTypesGetRouteTypesParamsWithHTTPClient creates a new RouteTypesGetRouteTypesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRouteTypesGetRouteTypesParamsWithHTTPClient(client *http.Client) *RouteTypesGetRouteTypesParams {
	var ()
	return &RouteTypesGetRouteTypesParams{
		HTTPClient: client,
	}
}

/*RouteTypesGetRouteTypesParams contains all the parameters to send to the API endpoint
for the route types get route types operation typically these are written to a http.Request
*/
type RouteTypesGetRouteTypesParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) WithTimeout(timeout time.Duration) *RouteTypesGetRouteTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) WithContext(ctx context.Context) *RouteTypesGetRouteTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) WithHTTPClient(client *http.Client) *RouteTypesGetRouteTypesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) WithDevid(devid *string) *RouteTypesGetRouteTypesParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithSignature adds the signature to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) WithSignature(signature *string) *RouteTypesGetRouteTypesParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) WithToken(token *string) *RouteTypesGetRouteTypesParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the route types get route types params
func (o *RouteTypesGetRouteTypesParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *RouteTypesGetRouteTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
