// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRunsForRunAndRouteTypeParams creates a new RunsForRunAndRouteTypeParams object
// with the default values initialized.
func NewRunsForRunAndRouteTypeParams() *RunsForRunAndRouteTypeParams {
	var ()
	return &RunsForRunAndRouteTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRunsForRunAndRouteTypeParamsWithTimeout creates a new RunsForRunAndRouteTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRunsForRunAndRouteTypeParamsWithTimeout(timeout time.Duration) *RunsForRunAndRouteTypeParams {
	var ()
	return &RunsForRunAndRouteTypeParams{

		timeout: timeout,
	}
}

// NewRunsForRunAndRouteTypeParamsWithContext creates a new RunsForRunAndRouteTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewRunsForRunAndRouteTypeParamsWithContext(ctx context.Context) *RunsForRunAndRouteTypeParams {
	var ()
	return &RunsForRunAndRouteTypeParams{

		Context: ctx,
	}
}

// NewRunsForRunAndRouteTypeParamsWithHTTPClient creates a new RunsForRunAndRouteTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRunsForRunAndRouteTypeParamsWithHTTPClient(client *http.Client) *RunsForRunAndRouteTypeParams {
	var ()
	return &RunsForRunAndRouteTypeParams{
		HTTPClient: client,
	}
}

/*RunsForRunAndRouteTypeParams contains all the parameters to send to the API endpoint
for the runs for run and route type operation typically these are written to a http.Request
*/
type RunsForRunAndRouteTypeParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*RouteType
	  Number identifying transport mode; values returned via RouteTypes API

	*/
	RouteType int32
	/*RunID
	  Identifier of a trip/service run; values returned by Runs API - /v3/route/{route_id} and Departures API

	*/
	RunID int32
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithTimeout(timeout time.Duration) *RunsForRunAndRouteTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithContext(ctx context.Context) *RunsForRunAndRouteTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithHTTPClient(client *http.Client) *RunsForRunAndRouteTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithDevid(devid *string) *RunsForRunAndRouteTypeParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithRouteType adds the routeType to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithRouteType(routeType int32) *RunsForRunAndRouteTypeParams {
	o.SetRouteType(routeType)
	return o
}

// SetRouteType adds the routeType to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetRouteType(routeType int32) {
	o.RouteType = routeType
}

// WithRunID adds the runID to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithRunID(runID int32) *RunsForRunAndRouteTypeParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetRunID(runID int32) {
	o.RunID = runID
}

// WithSignature adds the signature to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithSignature(signature *string) *RunsForRunAndRouteTypeParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) WithToken(token *string) *RunsForRunAndRouteTypeParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the runs for run and route type params
func (o *RunsForRunAndRouteTypeParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *RunsForRunAndRouteTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	// path param route_type
	if err := r.SetPathParam("route_type", swag.FormatInt32(o.RouteType)); err != nil {
		return err
	}

	// path param run_id
	if err := r.SetPathParam("run_id", swag.FormatInt32(o.RunID)); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
