// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRunsForRouteAndRouteTypeParams creates a new RunsForRouteAndRouteTypeParams object
// with the default values initialized.
func NewRunsForRouteAndRouteTypeParams() *RunsForRouteAndRouteTypeParams {
	var ()
	return &RunsForRouteAndRouteTypeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRunsForRouteAndRouteTypeParamsWithTimeout creates a new RunsForRouteAndRouteTypeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRunsForRouteAndRouteTypeParamsWithTimeout(timeout time.Duration) *RunsForRouteAndRouteTypeParams {
	var ()
	return &RunsForRouteAndRouteTypeParams{

		timeout: timeout,
	}
}

// NewRunsForRouteAndRouteTypeParamsWithContext creates a new RunsForRouteAndRouteTypeParams object
// with the default values initialized, and the ability to set a context for a request
func NewRunsForRouteAndRouteTypeParamsWithContext(ctx context.Context) *RunsForRouteAndRouteTypeParams {
	var ()
	return &RunsForRouteAndRouteTypeParams{

		Context: ctx,
	}
}

// NewRunsForRouteAndRouteTypeParamsWithHTTPClient creates a new RunsForRouteAndRouteTypeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRunsForRouteAndRouteTypeParamsWithHTTPClient(client *http.Client) *RunsForRouteAndRouteTypeParams {
	var ()
	return &RunsForRouteAndRouteTypeParams{
		HTTPClient: client,
	}
}

/*RunsForRouteAndRouteTypeParams contains all the parameters to send to the API endpoint
for the runs for route and route type operation typically these are written to a http.Request
*/
type RunsForRouteAndRouteTypeParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*RouteID
	  Identifier of route; values returned by Routes API - v3/routes.

	*/
	RouteID int32
	/*RouteType
	  Number identifying transport mode; values returned via RouteTypes API

	*/
	RouteType int32
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) WithTimeout(timeout time.Duration) *RunsForRouteAndRouteTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) WithContext(ctx context.Context) *RunsForRouteAndRouteTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) WithHTTPClient(client *http.Client) *RunsForRouteAndRouteTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) WithDevid(devid *string) *RunsForRouteAndRouteTypeParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithRouteID adds the routeID to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) WithRouteID(routeID int32) *RunsForRouteAndRouteTypeParams {
	o.SetRouteID(routeID)
	return o
}

// SetRouteID adds the routeId to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) SetRouteID(routeID int32) {
	o.RouteID = routeID
}

// WithRouteType adds the routeType to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) WithRouteType(routeType int32) *RunsForRouteAndRouteTypeParams {
	o.SetRouteType(routeType)
	return o
}

// SetRouteType adds the routeType to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) SetRouteType(routeType int32) {
	o.RouteType = routeType
}

// WithSignature adds the signature to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) WithSignature(signature *string) *RunsForRouteAndRouteTypeParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) WithToken(token *string) *RunsForRouteAndRouteTypeParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the runs for route and route type params
func (o *RunsForRouteAndRouteTypeParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *RunsForRouteAndRouteTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	// path param route_id
	if err := r.SetPathParam("route_id", swag.FormatInt32(o.RouteID)); err != nil {
		return err
	}

	// path param route_type
	if err := r.SetPathParam("route_type", swag.FormatInt32(o.RouteType)); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
