// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRunsForRunParams creates a new RunsForRunParams object
// with the default values initialized.
func NewRunsForRunParams() *RunsForRunParams {
	var ()
	return &RunsForRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRunsForRunParamsWithTimeout creates a new RunsForRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRunsForRunParamsWithTimeout(timeout time.Duration) *RunsForRunParams {
	var ()
	return &RunsForRunParams{

		timeout: timeout,
	}
}

// NewRunsForRunParamsWithContext creates a new RunsForRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewRunsForRunParamsWithContext(ctx context.Context) *RunsForRunParams {
	var ()
	return &RunsForRunParams{

		Context: ctx,
	}
}

// NewRunsForRunParamsWithHTTPClient creates a new RunsForRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRunsForRunParamsWithHTTPClient(client *http.Client) *RunsForRunParams {
	var ()
	return &RunsForRunParams{
		HTTPClient: client,
	}
}

/*RunsForRunParams contains all the parameters to send to the API endpoint
for the runs for run operation typically these are written to a http.Request
*/
type RunsForRunParams struct {

	/*Devid
	  Your developer id

	*/
	Devid *string
	/*RunID
	  Identifier of a trip/service run; values returned by Runs API - /v3/route/{route_id} and Departures API

	*/
	RunID int32
	/*Signature
	  Authentication signature for request

	*/
	Signature *string
	/*Token
	  Please ignore

	*/
	Token *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the runs for run params
func (o *RunsForRunParams) WithTimeout(timeout time.Duration) *RunsForRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the runs for run params
func (o *RunsForRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the runs for run params
func (o *RunsForRunParams) WithContext(ctx context.Context) *RunsForRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the runs for run params
func (o *RunsForRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the runs for run params
func (o *RunsForRunParams) WithHTTPClient(client *http.Client) *RunsForRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the runs for run params
func (o *RunsForRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevid adds the devid to the runs for run params
func (o *RunsForRunParams) WithDevid(devid *string) *RunsForRunParams {
	o.SetDevid(devid)
	return o
}

// SetDevid adds the devid to the runs for run params
func (o *RunsForRunParams) SetDevid(devid *string) {
	o.Devid = devid
}

// WithRunID adds the runID to the runs for run params
func (o *RunsForRunParams) WithRunID(runID int32) *RunsForRunParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the runs for run params
func (o *RunsForRunParams) SetRunID(runID int32) {
	o.RunID = runID
}

// WithSignature adds the signature to the runs for run params
func (o *RunsForRunParams) WithSignature(signature *string) *RunsForRunParams {
	o.SetSignature(signature)
	return o
}

// SetSignature adds the signature to the runs for run params
func (o *RunsForRunParams) SetSignature(signature *string) {
	o.Signature = signature
}

// WithToken adds the token to the runs for run params
func (o *RunsForRunParams) WithToken(token *string) *RunsForRunParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the runs for run params
func (o *RunsForRunParams) SetToken(token *string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *RunsForRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Devid != nil {

		// query param devid
		var qrDevid string
		if o.Devid != nil {
			qrDevid = *o.Devid
		}
		qDevid := qrDevid
		if qDevid != "" {
			if err := r.SetQueryParam("devid", qDevid); err != nil {
				return err
			}
		}

	}

	// path param run_id
	if err := r.SetPathParam("run_id", swag.FormatInt32(o.RunID)); err != nil {
		return err
	}

	if o.Signature != nil {

		// query param signature
		var qrSignature string
		if o.Signature != nil {
			qrSignature = *o.Signature
		}
		qSignature := qrSignature
		if qSignature != "" {
			if err := r.SetQueryParam("signature", qSignature); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken string
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := qrToken
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
