// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ronny/ptvapi/v3/models"
)

// RunsForRunReader is a Reader for the RunsForRun structure.
type RunsForRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunsForRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRunsForRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRunsForRunBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRunsForRunForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRunsForRunOK creates a RunsForRunOK with default headers values
func NewRunsForRunOK() *RunsForRunOK {
	return &RunsForRunOK{}
}

/*RunsForRunOK handles this case with default header values.

All trip/service run details for the specified run ID.
*/
type RunsForRunOK struct {
	Payload *models.V3RunsResponse
}

func (o *RunsForRunOK) Error() string {
	return fmt.Sprintf("[GET /v3/runs/{run_id}][%d] runsForRunOK  %+v", 200, o.Payload)
}

func (o *RunsForRunOK) GetPayload() *models.V3RunsResponse {
	return o.Payload
}

func (o *RunsForRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3RunsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunsForRunBadRequest creates a RunsForRunBadRequest with default headers values
func NewRunsForRunBadRequest() *RunsForRunBadRequest {
	return &RunsForRunBadRequest{}
}

/*RunsForRunBadRequest handles this case with default header values.

Invalid Request
*/
type RunsForRunBadRequest struct {
	Payload *models.V3ErrorResponse
}

func (o *RunsForRunBadRequest) Error() string {
	return fmt.Sprintf("[GET /v3/runs/{run_id}][%d] runsForRunBadRequest  %+v", 400, o.Payload)
}

func (o *RunsForRunBadRequest) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *RunsForRunBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRunsForRunForbidden creates a RunsForRunForbidden with default headers values
func NewRunsForRunForbidden() *RunsForRunForbidden {
	return &RunsForRunForbidden{}
}

/*RunsForRunForbidden handles this case with default header values.

Access Denied
*/
type RunsForRunForbidden struct {
	Payload *models.V3ErrorResponse
}

func (o *RunsForRunForbidden) Error() string {
	return fmt.Sprintf("[GET /v3/runs/{run_id}][%d] runsForRunForbidden  %+v", 403, o.Payload)
}

func (o *RunsForRunForbidden) GetPayload() *models.V3ErrorResponse {
	return o.Payload
}

func (o *RunsForRunForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V3ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
