// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3BulkDeparturesRouteDirectionResponse v3 bulk departures route direction response
// swagger:model V3.BulkDeparturesRouteDirectionResponse
type V3BulkDeparturesRouteDirectionResponse struct {

	// Direction of travel identifier
	DirectionID int32 `json:"direction_id,omitempty"`

	// Name of direction of travel
	DirectionName string `json:"direction_name,omitempty"`

	// Route identifier
	RouteID string `json:"route_id,omitempty"`
}

// Validate validates this v3 bulk departures route direction response
func (m *V3BulkDeparturesRouteDirectionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3BulkDeparturesRouteDirectionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3BulkDeparturesRouteDirectionResponse) UnmarshalBinary(b []byte) error {
	var res V3BulkDeparturesRouteDirectionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
