// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3Direction v3 direction
// swagger:model V3.Direction
type V3Direction struct {

	// Direction of travel identifier
	DirectionID int32 `json:"direction_id,omitempty"`

	// Name of direction of travel
	DirectionName string `json:"direction_name,omitempty"`

	// Route identifier
	RouteID int32 `json:"route_id,omitempty"`

	// Transport mode identifier
	RouteType int32 `json:"route_type,omitempty"`
}

// Validate validates this v3 direction
func (m *V3Direction) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3Direction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3Direction) UnmarshalBinary(b []byte) error {
	var res V3Direction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
