// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// V3DisruptionResponse v3 disruption response
// swagger:model V3.DisruptionResponse
type V3DisruptionResponse struct {

	// Disruption information applicable to relevant routes or stops
	Disruption *V3Disruption `json:"disruption,omitempty"`

	// API Status / Metadata
	Status *V3Status `json:"status,omitempty"`
}

// Validate validates this v3 disruption response
func (m *V3DisruptionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisruption(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3DisruptionResponse) validateDisruption(formats strfmt.Registry) error {

	if swag.IsZero(m.Disruption) { // not required
		return nil
	}

	if m.Disruption != nil {
		if err := m.Disruption.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("disruption")
			}
			return err
		}
	}

	return nil
}

func (m *V3DisruptionResponse) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3DisruptionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3DisruptionResponse) UnmarshalBinary(b []byte) error {
	var res V3DisruptionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
