// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// V3DisruptionModesResponse v3 disruption modes response
// swagger:model V3.DisruptionModesResponse
type V3DisruptionModesResponse struct {

	// Transport mode identifiers
	DisruptionModes []*V3DisruptionMode `json:"disruption_modes"`

	// API Status / Metadata
	Status *V3Status `json:"status,omitempty"`
}

// Validate validates this v3 disruption modes response
func (m *V3DisruptionModesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisruptionModes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3DisruptionModesResponse) validateDisruptionModes(formats strfmt.Registry) error {

	if swag.IsZero(m.DisruptionModes) { // not required
		return nil
	}

	for i := 0; i < len(m.DisruptionModes); i++ {
		if swag.IsZero(m.DisruptionModes[i]) { // not required
			continue
		}

		if m.DisruptionModes[i] != nil {
			if err := m.DisruptionModes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("disruption_modes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V3DisruptionModesResponse) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3DisruptionModesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3DisruptionModesResponse) UnmarshalBinary(b []byte) error {
	var res V3DisruptionModesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
