// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3DisruptionDirection v3 disruption direction
// swagger:model V3.DisruptionDirection
type V3DisruptionDirection struct {

	// Direction of travel identifier
	DirectionID int32 `json:"direction_id,omitempty"`

	// Name of direction of travel
	DirectionName string `json:"direction_name,omitempty"`

	// Route and direction of travel combination identifier
	RouteDirectionID int32 `json:"route_direction_id,omitempty"`

	// Time of service to which disruption applies, in 24 hour clock format (HH:MM:SS) AEDT/AEST; returns null if disruption applies to multiple (or no) services
	ServiceTime string `json:"service_time,omitempty"`
}

// Validate validates this v3 disruption direction
func (m *V3DisruptionDirection) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3DisruptionDirection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3DisruptionDirection) UnmarshalBinary(b []byte) error {
	var res V3DisruptionDirection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
