// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3OutletParameters v3 outlet parameters
// swagger:model V3.OutletParameters
type V3OutletParameters struct {

	// Maximum number of results returned (default = 30)
	MaxResults int32 `json:"max_results,omitempty"`
}

// Validate validates this v3 outlet parameters
func (m *V3OutletParameters) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3OutletParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3OutletParameters) UnmarshalBinary(b []byte) error {
	var res V3OutletParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
