// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3RouteType v3 route type
// swagger:model V3.RouteType
type V3RouteType struct {

	// Transport mode identifier
	RouteType int32 `json:"route_type,omitempty"`

	// Name of transport mode
	RouteTypeName string `json:"route_type_name,omitempty"`
}

// Validate validates this v3 route type
func (m *V3RouteType) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3RouteType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3RouteType) UnmarshalBinary(b []byte) error {
	var res V3RouteType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
