// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3Route v3 route
// swagger:model V3.Route
type V3Route struct {

	// GTFS Identifer of the route
	RouteGtfsID string `json:"route_gtfs_id,omitempty"`

	// Route identifier
	RouteID int32 `json:"route_id,omitempty"`

	// Name of route
	RouteName string `json:"route_name,omitempty"`

	// Route number presented to public (nb. not route_id)
	RouteNumber string `json:"route_number,omitempty"`

	// Transport mode identifier
	RouteType int32 `json:"route_type,omitempty"`
}

// Validate validates this v3 route
func (m *V3Route) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3Route) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3Route) UnmarshalBinary(b []byte) error {
	var res V3Route
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
