// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3StopsByDistanceResponse v3 stops by distance response
// swagger:model V3.StopsByDistanceResponse
type V3StopsByDistanceResponse struct {

	// Disruption information applicable to relevant routes or stops
	Disruptions map[string]V3Disruption `json:"disruptions,omitempty"`

	// API Status / Metadata
	Status *V3Status `json:"status,omitempty"`

	// Train stations, tram stops, bus stops, regional coach stops or Night Bus stops
	Stops []*V3StopGeosearch `json:"stops"`
}

// Validate validates this v3 stops by distance response
func (m *V3StopsByDistanceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisruptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStops(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3StopsByDistanceResponse) validateDisruptions(formats strfmt.Registry) error {

	if swag.IsZero(m.Disruptions) { // not required
		return nil
	}

	for k := range m.Disruptions {

		if err := validate.Required("disruptions"+"."+k, "body", m.Disruptions[k]); err != nil {
			return err
		}
		if val, ok := m.Disruptions[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *V3StopsByDistanceResponse) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *V3StopsByDistanceResponse) validateStops(formats strfmt.Registry) error {

	if swag.IsZero(m.Stops) { // not required
		return nil
	}

	for i := 0; i < len(m.Stops); i++ {
		if swag.IsZero(m.Stops[i]) { // not required
			continue
		}

		if m.Stops[i] != nil {
			if err := m.Stops[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stops" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3StopsByDistanceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3StopsByDistanceResponse) UnmarshalBinary(b []byte) error {
	var res V3StopsByDistanceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
