// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// V3StopLocation v3 stop location
// swagger:model V3.StopLocation
type V3StopLocation struct {

	// GPS coordinates of the stop
	Gps *V3StopGps `json:"gps,omitempty"`
}

// Validate validates this v3 stop location
func (m *V3StopLocation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3StopLocation) validateGps(formats strfmt.Registry) error {

	if swag.IsZero(m.Gps) { // not required
		return nil
	}

	if m.Gps != nil {
		if err := m.Gps.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gps")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3StopLocation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3StopLocation) UnmarshalBinary(b []byte) error {
	var res V3StopLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
