// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3StopStaffing v3 stop staffing
// swagger:model V3.StopStaffing
type V3StopStaffing struct {

	// Stop staffing hours
	FriAmFrom string `json:"fri_am_from,omitempty"`

	// Stop staffing hours
	FriAmTo string `json:"fri_am_to,omitempty"`

	// Stop staffing hours
	FriPmFrom string `json:"fri_pm_from,omitempty"`

	// Stop staffing hours
	FriPmTo string `json:"fri_pm_to,omitempty"`

	// Stop staffing hours
	MonAmFrom string `json:"mon_am_from,omitempty"`

	// Stop staffing hours
	MonAmTo string `json:"mon_am_to,omitempty"`

	// Stop staffing hours
	MonPmFrom string `json:"mon_pm_from,omitempty"`

	// Stop staffing hours
	MonPmTo string `json:"mon_pm_to,omitempty"`

	// Stop staffing hours
	PhAdditionalText string `json:"ph_additional_text,omitempty"`

	// Stop staffing hours
	PhFrom string `json:"ph_from,omitempty"`

	// Stop staffing hours
	PhTo string `json:"ph_to,omitempty"`

	// Stop staffing hours
	SatAmFrom string `json:"sat_am_from,omitempty"`

	// Stop staffing hours
	SatAmTo string `json:"sat_am_to,omitempty"`

	// Stop staffing hours
	SatPmFrom string `json:"sat_pm_from,omitempty"`

	// Stop staffing hours
	SatPmTo string `json:"sat_pm_to,omitempty"`

	// Stop staffing hours
	SunAmFrom string `json:"sun_am_from,omitempty"`

	// Stop staffing hours
	SunAmTo string `json:"sun_am_to,omitempty"`

	// Stop staffing hours
	SunPmFrom string `json:"sun_pm_from,omitempty"`

	// Stop staffing hours
	SunPmTo string `json:"sun_pm_to,omitempty"`

	// Stop staffing hours
	ThuAmFrom string `json:"thu_am_from,omitempty"`

	// Stop staffing hours
	ThuAmTo string `json:"thu_am_to,omitempty"`

	// Stop staffing hours
	ThuPmFrom string `json:"thu_pm_from,omitempty"`

	// Stop staffing hours
	ThuPmTo string `json:"thu_pm_to,omitempty"`

	// Stop staffing hours
	TueAmFrom string `json:"tue_am_from,omitempty"`

	// Stop staffing hours
	TueAmTo string `json:"tue_am_to,omitempty"`

	// Stop staffing hours
	TuePmFrom string `json:"tue_pm_from,omitempty"`

	// Stop staffing hours
	TuePmTo string `json:"tue_pm_to,omitempty"`

	// Stop staffing hours
	WedAmFrom string `json:"wed_am_from,omitempty"`

	// Stop staffing hours
	WedAmTo string `json:"wed_am_to,omitempty"`

	// Stop staffing hours
	WedPmTo string `json:"wed_pm_To,omitempty"`

	// Stop staffing hours
	WedPmFrom string `json:"wed_pm_from,omitempty"`
}

// Validate validates this v3 stop staffing
func (m *V3StopStaffing) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3StopStaffing) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3StopStaffing) UnmarshalBinary(b []byte) error {
	var res V3StopStaffing
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
