// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V3StopResponse v3 stop response
// swagger:model V3.StopResponse
type V3StopResponse struct {

	// Disruption information applicable to relevant routes or stops
	Disruptions map[string]V3Disruption `json:"disruptions,omitempty"`

	// API Status / Metadata
	Status *V3Status `json:"status,omitempty"`

	// A metropolitan or V/Line train station
	Stop *V3StopDetails `json:"stop,omitempty"`
}

// Validate validates this v3 stop response
func (m *V3StopResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisruptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStop(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V3StopResponse) validateDisruptions(formats strfmt.Registry) error {

	if swag.IsZero(m.Disruptions) { // not required
		return nil
	}

	for k := range m.Disruptions {

		if err := validate.Required("disruptions"+"."+k, "body", m.Disruptions[k]); err != nil {
			return err
		}
		if val, ok := m.Disruptions[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *V3StopResponse) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *V3StopResponse) validateStop(formats strfmt.Registry) error {

	if swag.IsZero(m.Stop) { // not required
		return nil
	}

	if m.Stop != nil {
		if err := m.Stop.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stop")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V3StopResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3StopResponse) UnmarshalBinary(b []byte) error {
	var res V3StopResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
