// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3StopGps v3 stop gps
// swagger:model V3.StopGps
type V3StopGps struct {

	// Geographic coordinate of latitude at stop
	Latitude float32 `json:"latitude,omitempty"`

	// Geographic coordinate of longitude at stop
	Longitude float32 `json:"longitude,omitempty"`
}

// Validate validates this v3 stop gps
func (m *V3StopGps) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3StopGps) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3StopGps) UnmarshalBinary(b []byte) error {
	var res V3StopGps
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
