// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3StopBase v3 stop base
// swagger:model V3.StopBase
type V3StopBase struct {

	// Stop identifier
	StopID int32 `json:"stop_id,omitempty"`

	// Name of stop
	StopName string `json:"stop_name,omitempty"`
}

// Validate validates this v3 stop base
func (m *V3StopBase) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3StopBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3StopBase) UnmarshalBinary(b []byte) error {
	var res V3StopBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
