// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V3VehiclePosition v3 vehicle position
// swagger:model V3.VehiclePosition
type V3VehiclePosition struct {

	// Compass bearing of the vehicle when known, clockwise from True North, i.e., 0 is North and 90 is East. May be null.
	//             Only available for some bus runs.
	Bearing float32 `json:"bearing,omitempty"`

	// Geographic coordinate of latitude of the vehicle when known. May be null.
	//             Only available for some bus runs.
	Latitude float32 `json:"latitude,omitempty"`

	// Geographic coordinate of longitude of the vehicle when known.
	//             Only available for some bus runs.
	Longitude float32 `json:"longitude,omitempty"`

	// Supplier of vehicle position data.
	// Read Only: true
	Supplier string `json:"supplier,omitempty"`
}

// Validate validates this v3 vehicle position
func (m *V3VehiclePosition) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V3VehiclePosition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V3VehiclePosition) UnmarshalBinary(b []byte) error {
	var res V3VehiclePosition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
